version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
  
  authservice:
    container_name: AuthService
    build:
      context: "."
      dockerfile: /AuthService/Dockerfile
    ports: 
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - database
    restart: unless-stopped

  modseneventservice:
    build:
      context: "."
      dockerfile: /ModsenEventService/ModsenEventService.API/Dockerfile
    ports:
      - 9001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - database
    restart: unless-stopped
